# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Workflow Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, Github Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-lates
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
